### ISSUE TITLE
explorer should only return reliable, correctly configured gateways

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgateway#35]
Right now, the only check we do on our side is checking for the dns_nameserver in the response, but that doesn't prevent misconfigured gateways to be still shown. deployment of gateways should be bit more strict, with some kind of sanity check before accepting/ sending them around for the SDK to use

**Comment by zaibon** [comment]
We could had a check in the gateway itself that verifies the DNS configuration for the managed domain are correct. Both at startup and at regular interval

**Comment by xmonader** [comment]
recently someone added a gateway and claimed to be managing domains that are already controlled by threefold ava.tf, gateway.tf, 3x0.me 

![image](https://user-images.githubusercontent.com/64129/100740011-b0648280-33e0-11eb-8280-2ed841faab86.png)

**Comment by muhamadazmy** [comment]
This issue should be split into 2 issues:
- One related not booting nodes (or gateways) in the wrong farm. since now a node (or a gateway) just uses a farmer id and the explorer has noway to verify if this is really managed by that farm or an impersonator. There is already another issue to track this here https://github.com/threefoldtech/zos/issues/1129

- The other issue is related to the gateway directly. we need to verify that the domain name configured is actually managed by this gateway instance. Hence we have the following possible solutions:
  - Solution 1: Check the IP of the request and make sure it matches the IP address returned by `digging` the domain name.
  - Solution 2: The explorer tries to connect back to the gateway (over the domain name) with a challenge, the gateway must respond back with a signature for that  challenge with the gateway identity (sk). If it replies we validate that this gateway is actually listening on that domain name.
  - Solution 3: I think that is the easiest, the gateway must configure a TXT entry with it's public key. In that case the explorer can dig the domain, and if the TXT is received that matches the gateway identity then it should be accepted
